theme: jekyll-theme-minimal
title: Keerati's Portfolio
description:Robotics researcher interested in multi-agent control, distributed systems, non-holomic systems, and swarm intelligence.
Proficient in Python, C/C++, Linux, Git, and robot control software such as ROS.
With nine years of experience and a degree in engineering, I am immediately ready to contribute.
Rapid adaptability to new challenges and surroundings. 
logo: /assets/css/pic.jpg
